### PR TITLE
adding FileManager package with 2 functions to parse markdown to html…

### PR DESCRIPTION
**Pull request by heryck237**
Adding FileManager paackage and commonmark dependancy in the pom.xml

### CODE REVIEW

**Comment by nicrausaz** [comment]
Hello, can you please write some tests for the two methods that you implemented ?

Also you can run `mvn spotless:apply` before commiting to apply (we will automatize this later)

**Review by nicrausaz — APPROVED** [review]
Nice !

**Review by maxscharwath — CHANGES_REQUESTED** [review]
I think it's best to edit test name: use FileManagerTest.java instead of AppTest.java

**Review by maxscharwath — APPROVED** [review]
Now it's ok !

**Pull request merged**
